'use strict';
let mapa =[
  {"indicador": "IQGoperação", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A"]},
  {"indicador": "IAPC-dde", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "NA"]},
  {"indicador": "IEFP", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AR"]},
  {"indicador": "IACCIF", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IEC", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TASP-sub", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IRIF", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "IEPoperação", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "IKick", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AA"]},
  {"indicador": "TPerf C1 (0 - 500 m)", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "CE", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "GOG (US$)", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AA"]},
  {"indicador": "EBITDAX", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IROI - MM US$", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IROI - LIBRA", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "GOG", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "COGOunidade", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "IPAP", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "Tperf Pos-sal", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "Tperf Presal Extra-BS", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "PcompPOLEO", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "PROCOP", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  
  
  {"indicador": "ASP-t", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AR"]},
  {"indicador": "ISP-t", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TASP-t", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ISE", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IUGA", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "POLEO", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "PTP", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "ROCE - E&P", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "ResPVD", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TFCA", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "DGAS", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "PD", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IROI-IS", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ICPM-SO", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "Poço", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IDTM", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AA"]},
  {"indicador": "PE3", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "VDER", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IPE", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IPNI", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IEP", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "PGAS (S/ Liq.)", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  
  
  {"indicador": "FRP", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IADS", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AR"]},
  {"indicador": "CD", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "CE (S/P)", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "CTPP", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "EGAS", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "GCO", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "IACM", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "IMA", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IRO", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IROI", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AR"]},
  {"indicador": "IROI-DP", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IROI-EXP", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "AA"]},
  {"indicador": "IQG", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TOR", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IACV", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IACworkover", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "POLEOoperação", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "DGASoperação", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IUGAoperação", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IARItopside", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ICPItopside", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  
  {"indicador": "ICPMtopside", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IAPprojpoçodp", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ICCL", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IAFP", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ICCustos", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ISBOP", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IEW", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "TASP-m", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "ITPAX", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ICPIsub-serv", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IARIsub-serv", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IROI-PGSU", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ISPQ", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IACCL", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IAPinst.dutos_UEH", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "IAPinst.eq.sub", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ICFF", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "GFPRCpoço", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TCompBS", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TComp-outros", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TPerfBS", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "TPerf-poçoexp", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  
  {"indicador": "IACworkoverPROEF", "status": ["EE", "EE", "EE", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ASP-sub", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ISP-m", "status": ["N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ISP-sub", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "ASP-m", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "VAZO", "status": ["N/A", "N/A", "N/A", "N/A", "A", "N/A", "A", "A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A"]},
  {"indicador": "Potencial", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]},
  {"indicador": "IACprojpoçodp", "status": ["EE", "N/A", "N/A", "EE", "N/A", "EE", "N/A", "EE", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A", "EE", "EE", "N/A"]}
]

module.exports = mapa;